name: BUSCU

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Tải Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/Windows2019RDP-US-MMDYT/main/Files/nssm.exe -OutFile nssm.exe
    - name: Chép NSSM & Ngrok Vào thư mục Windows.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Kết nối đến tài khoản Ngrok của bạn
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Tải những files quan trọng.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/Windows2019RDP-US-MMDYT/main/Files/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/Windows2019RDP-US-MMDYT/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/YOUR_GITHUB_USERNAME/Windows2019RDP-US-MMDYT/main/Files/loop.bat -OutFile loop.bat
    - name: Làm những files YML cho Ngrok.
      run: start NGROK-AP.bat
    - name: Bật quyền truy cập vào RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tạo Tunnel
      run: sc start ngrok
    - name: Kết nối đến RDP của bạn, 2 nhân 8gb ram.
      run: cmd /c NGROK-CHECK.bat
    - name: Tất cả đã được làm xong! Bạn có thể đóng Tab ngay bây giờ! Thời gian tối đa RDP của bạn là 6h.
      run: cmd /c loop.bat 
      
    
